// Type color palettes for dynamic theming across the app
// Each type maps to Tailwind classes for backgrounds, text, gradients, badges, and stat bars

export const TYPE_COLORS = {
  normal: {
    bg: 'bg-stone-400',
    bgLight: 'bg-stone-100',
    text: 'text-stone-50',
    textDark: 'text-stone-700',
    gradient: 'from-stone-400 to-stone-500',
    border: 'border-stone-300',
    ring: 'ring-stone-300',
    badge: 'bg-stone-400/90 text-white',
    hex: '#a8a878',
  },
  fire: {
    bg: 'bg-orange-500',
    bgLight: 'bg-orange-100',
    text: 'text-orange-50',
    textDark: 'text-orange-700',
    gradient: 'from-orange-500 to-red-600',
    border: 'border-orange-300',
    ring: 'ring-orange-300',
    badge: 'bg-orange-500/90 text-white',
    hex: '#f08030',
  },
  water: {
    bg: 'bg-blue-500',
    bgLight: 'bg-blue-100',
    text: 'text-blue-50',
    textDark: 'text-blue-700',
    gradient: 'from-blue-500 to-indigo-600',
    border: 'border-blue-300',
    ring: 'ring-blue-300',
    badge: 'bg-blue-500/90 text-white',
    hex: '#6890f0',
  },
  electric: {
    bg: 'bg-yellow-400',
    bgLight: 'bg-yellow-100',
    text: 'text-yellow-50',
    textDark: 'text-yellow-700',
    gradient: 'from-yellow-400 to-amber-500',
    border: 'border-yellow-300',
    ring: 'ring-yellow-300',
    badge: 'bg-yellow-400/90 text-white',
    hex: '#f8d030',
  },
  grass: {
    bg: 'bg-emerald-500',
    bgLight: 'bg-emerald-100',
    text: 'text-emerald-50',
    textDark: 'text-emerald-700',
    gradient: 'from-emerald-500 to-green-600',
    border: 'border-emerald-300',
    ring: 'ring-emerald-300',
    badge: 'bg-emerald-500/90 text-white',
    hex: '#78c850',
  },
  ice: {
    bg: 'bg-cyan-400',
    bgLight: 'bg-cyan-100',
    text: 'text-cyan-50',
    textDark: 'text-cyan-700',
    gradient: 'from-cyan-400 to-sky-500',
    border: 'border-cyan-300',
    ring: 'ring-cyan-300',
    badge: 'bg-cyan-400/90 text-white',
    hex: '#98d8d8',
  },
  fighting: {
    bg: 'bg-red-700',
    bgLight: 'bg-red-100',
    text: 'text-red-50',
    textDark: 'text-red-800',
    gradient: 'from-red-700 to-red-900',
    border: 'border-red-400',
    ring: 'ring-red-400',
    badge: 'bg-red-700/90 text-white',
    hex: '#c03028',
  },
  poison: {
    bg: 'bg-purple-500',
    bgLight: 'bg-purple-100',
    text: 'text-purple-50',
    textDark: 'text-purple-700',
    gradient: 'from-purple-500 to-purple-700',
    border: 'border-purple-300',
    ring: 'ring-purple-300',
    badge: 'bg-purple-500/90 text-white',
    hex: '#a040a0',
  },
  ground: {
    bg: 'bg-amber-600',
    bgLight: 'bg-amber-100',
    text: 'text-amber-50',
    textDark: 'text-amber-800',
    gradient: 'from-amber-600 to-yellow-700',
    border: 'border-amber-400',
    ring: 'ring-amber-400',
    badge: 'bg-amber-600/90 text-white',
    hex: '#e0c068',
  },
  flying: {
    bg: 'bg-indigo-400',
    bgLight: 'bg-indigo-100',
    text: 'text-indigo-50',
    textDark: 'text-indigo-700',
    gradient: 'from-indigo-400 to-violet-500',
    border: 'border-indigo-300',
    ring: 'ring-indigo-300',
    badge: 'bg-indigo-400/90 text-white',
    hex: '#a890f0',
  },
  psychic: {
    bg: 'bg-pink-500',
    bgLight: 'bg-pink-100',
    text: 'text-pink-50',
    textDark: 'text-pink-700',
    gradient: 'from-pink-500 to-rose-600',
    border: 'border-pink-300',
    ring: 'ring-pink-300',
    badge: 'bg-pink-500/90 text-white',
    hex: '#f85888',
  },
  bug: {
    bg: 'bg-lime-500',
    bgLight: 'bg-lime-100',
    text: 'text-lime-50',
    textDark: 'text-lime-800',
    gradient: 'from-lime-500 to-green-600',
    border: 'border-lime-300',
    ring: 'ring-lime-300',
    badge: 'bg-lime-500/90 text-white',
    hex: '#a8b820',
  },
  rock: {
    bg: 'bg-yellow-700',
    bgLight: 'bg-yellow-100',
    text: 'text-yellow-50',
    textDark: 'text-yellow-800',
    gradient: 'from-yellow-700 to-amber-800',
    border: 'border-yellow-500',
    ring: 'ring-yellow-500',
    badge: 'bg-yellow-700/90 text-white',
    hex: '#b8a038',
  },
  ghost: {
    bg: 'bg-violet-600',
    bgLight: 'bg-violet-100',
    text: 'text-violet-50',
    textDark: 'text-violet-800',
    gradient: 'from-violet-600 to-purple-800',
    border: 'border-violet-400',
    ring: 'ring-violet-400',
    badge: 'bg-violet-600/90 text-white',
    hex: '#705898',
  },
  dragon: {
    bg: 'bg-indigo-700',
    bgLight: 'bg-indigo-100',
    text: 'text-indigo-50',
    textDark: 'text-indigo-800',
    gradient: 'from-indigo-700 to-violet-800',
    border: 'border-indigo-400',
    ring: 'ring-indigo-400',
    badge: 'bg-indigo-700/90 text-white',
    hex: '#7038f8',
  },
  dark: {
    bg: 'bg-stone-700',
    bgLight: 'bg-stone-200',
    text: 'text-stone-50',
    textDark: 'text-stone-800',
    gradient: 'from-stone-700 to-stone-900',
    border: 'border-stone-500',
    ring: 'ring-stone-500',
    badge: 'bg-stone-700/90 text-white',
    hex: '#705848',
  },
  steel: {
    bg: 'bg-slate-400',
    bgLight: 'bg-slate-100',
    text: 'text-slate-50',
    textDark: 'text-slate-700',
    gradient: 'from-slate-400 to-slate-600',
    border: 'border-slate-300',
    ring: 'ring-slate-300',
    badge: 'bg-slate-400/90 text-white',
    hex: '#b8b8d0',
  },
  fairy: {
    bg: 'bg-pink-400',
    bgLight: 'bg-pink-100',
    text: 'text-pink-50',
    textDark: 'text-pink-700',
    gradient: 'from-pink-400 to-rose-400',
    border: 'border-pink-300',
    ring: 'ring-pink-300',
    badge: 'bg-pink-400/90 text-white',
    hex: '#ee99ac',
  },
}

// Get color config for a type, with a safe fallback
export function getTypeColor(typeName) {
  return TYPE_COLORS[typeName] || TYPE_COLORS.normal
}

// Get the primary type color from a pokemon's types array
export function getPrimaryTypeColor(types) {
  if (!types || types.length === 0) return TYPE_COLORS.normal
  return getTypeColor(types[0].type.name)
}

// All type names
export const ALL_TYPES = Object.keys(TYPE_COLORS)
